import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.jsx',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['"Public Sans"', '"Noto Sans"', ...defaultTheme.fontFamily.sans],
                outfit: ['"Outfit"', 'sans-serif'],
                publicSans: ['"Public Sans"', 'sans-serif'],
            },
            colors: {
                'fp-green': '#24402F',
                'fp-green-dark': '#16281D',
                'fp-green-tint': '#EDEFEA',
                'fp-gold': '#C8901F',
                'fp-gold-light': '#E8B14A',
                'fp-gold-tint': '#FBF0DA',
                'fp-sand': '#FAF6EF',
                'fp-sand-subtle': '#FBF8F2',
                'fp-sand-card': '#F6F3EB',
                'fp-border': '#EAE3D6',
                'fp-border-dark': '#E2DACB',
                'fp-ink': '#16241C',
                'fp-ink-muted': '#5F6E63',
                'fp-ink-secondary': '#6B7A70',
                'fp-red': '#EE3B23',
                'fp-red-dark': '#A32A17',
                'fp-red-tint': '#FDEAE6',
                'fp-emerald': '#2F7A5A',
                'fp-emerald-tint': '#E7F2EC',
                'tea_green': {
                    DEFAULT: '#c9e4ca',
                    100: '#1d391e',
                    200: '#39723b',
                    300: '#57aa5a',
                    400: '#90c792',
                    500: '#c9e4ca',
                    600: '#d4e9d4',
                    700: '#deefdf',
                    800: '#e9f4ea',
                    900: '#f4faf4',
                },
                'muted_teal': {
                    DEFAULT: '#87bba2',
                    100: '#172920',
                    200: '#2e5241',
                    300: '#457b61',
                    400: '#5da482',
                    500: '#87bba2',
                    600: '#9ec9b4',
                    700: '#b7d6c7',
                    800: '#cfe4da',
                    900: '#e7f1ec',
                },
                'pacific_cyan': {
                    DEFAULT: '#55828b',
                    100: '#111a1c',
                    200: '#223438',
                    300: '#334e53',
                    400: '#44686f',
                    500: '#55828b',
                    600: '#719fa8',
                    700: '#95b7be',
                    800: '#b8cfd4',
                    900: '#dce7e9',
                },
                'dark_slate_grey': {
                    DEFAULT: '#3b6064',
                    100: '#0c1314',
                    200: '#172628',
                    300: '#23393c',
                    400: '#2f4c50',
                    500: '#3b6064',
                    600: '#558a90',
                    700: '#7aabb1',
                    800: '#a6c7cb',
                    900: '#d3e3e5',
                },
                'charcoal_blue': {
                    DEFAULT: '#364958',
                    100: '#0b0f12',
                    200: '#161d23',
                    300: '#212c35',
                    400: '#2b3b47',
                    500: '#364958',
                    600: '#527086',
                    700: '#7694ab',
                    800: '#a4b8c7',
                    900: '#d1dbe3',
                },
                'copper': {
                    DEFAULT: '#c78f54',
                    light: '#d6a574',
                    dark: '#b0793e',
                    soft: '#f9f3ec',
                },
                'pmcc-primary': '#364958',
                'pmcc-primary-dark': '#212c35',
                'pmcc-accent': '#c78f54',
                'pmcc-accent-soft': '#f9f3ec',
                'pmcc-bg-citizen': '#f4faf4',
                'pmcc-bg-staff': '#e7f1ec',
                'pmcc-surface': '#FFFFFF',
                'pmcc-border': '#d3e3e5',
                'pmcc-text-primary': '#0b0f12',
                'pmcc-text-secondary': '#3b6064',
                'pmcc-status-pending': '#55828b',
                'pmcc-status-investigation': '#c78f54',
                'pmcc-status-resolved': '#39723b',
                'pmcc-status-rejected': '#B3352A',
            },
        },
    },

    plugins: [forms],
};
